// src/lib/components/GtaSettingsDialog.svelte
<script lang="ts">
  import Dialog from './ui/Dialog.svelte'
  import { api } from '../api'
  import { getSettingDefinition, humanizeKey, SETTING_CATEGORIES } from '../gtaSettingsMap'
  import type { GtaSettingsDocument, GtaSettingsItem } from '../types'

  let {
    open = $bindable(false),
    clientId
  }: {
    open?: boolean
    clientId: string | null
  } = $props()

  let doc = $state<GtaSettingsDocument>({ rootName: 'Settings', items: [] })
  let loading = $state(false)
  let dirty = $state(false)
  let error = $state<string | null>(null)
  let savedFlash = $state(false)

  $effect(() => {
    if (!open || !clientId) return
    void load(clientId)
  })

  async function load(id: string): Promise<void> {
    loading = true
    error = null
    dirty = false
    try {
      doc = await api.getClientGtaSettings(id)
    } catch (e) {
      error = String(e)
    } finally {
      loading = false
    }
  }

  function settingNameFor(item: GtaSettingsItem): string {
    const parts = item.path.split('/').filter(Boolean)
    return parts[parts.length - 1] ?? item.path
  }

  const categorized = $derived.by(() => {
    const groups: Record<string, { item: GtaSettingsItem; index: number }[]> = {}
    doc.items.forEach((item, index) => {
      const name = settingNameFor(item)
      const def = getSettingDefinition(name)
      const category = def?.category || 'Other'
      ;(groups[category] ??= []).push({ item, index })
    })

    const sorted: [string, { item: GtaSettingsItem; index: number }[]][] = []
    for (const cat of SETTING_CATEGORIES) {
      if (groups[cat]?.length) sorted.push([cat, groups[cat]])
    }
    if (groups['Other']?.length) sorted.push(['Other', groups['Other']])
    return sorted
  })

  function updateAttribute(index: number, attrKey: string, value: string): void {
    doc.items[index].attributes[attrKey] = value
    dirty = true
  }

  async function save(): Promise<void> {
    if (!clientId) return
    try {
      await api.saveClientGtaSettings(clientId, $state.snapshot(doc))
      dirty = false
      savedFlash = true
      setTimeout(() => (savedFlash = false), 1200)
    } catch (e) {
      error = String(e)
    }
  }

  async function importFromGame(): Promise<void> {
    if (!clientId) return
    loading = true
    error = null
    try {
      doc = await api.importGtaSettingsFromDocuments(clientId)
      dirty = false
    } catch (e) {
      error = String(e)
    } finally {
      loading = false
    }
  }

  async function loadTemplate(): Promise<void> {
    if (!clientId) return
    loading = true
    error = null
    try {
      doc = await api.importGtaSettingsFromTemplate(clientId)
      dirty = false
    } catch (e) {
      error = String(e)
    } finally {
      loading = false
    }
  }
</script>

<Dialog
  bind:open
  title="GTA V Settings Editor"
  description="Edit this client's gta5_settings.xml. Saved in the client folder and applied when you launch with GTA Settings enabled."
  maxWidth="max-w-3xl"
>
  <div class="mt-3 space-y-3">
    <div class="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
      <span>Root element:</span>
      <span class="font-medium text-foreground">{doc.rootName}</span>
      <span>·</span>
      <span>{doc.items.length} entries</span>
      {#if loading}<span>· Loading…</span>{/if}
    </div>

    {#if error}
      <div class="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm">
        {error}
      </div>
    {/if}

    {#if !loading}
      {#if categorized.length === 0}
        <div class="rounded-md border border-dashed border-border p-4 text-sm text-muted-foreground">
          No settings found. Import from the game or load the example template below.
        </div>
      {:else}
        {#each categorized as [category, entries] (category)}
          <div class="rounded-md border border-border p-4">
            <div class="mb-3 flex items-center gap-2">
              <div class="h-1 w-1 rounded-full bg-primary"></div>
              <div class="text-sm font-semibold">{category}</div>
              <div class="text-xs text-muted-foreground">({entries.length})</div>
            </div>

            <div class="grid gap-3 sm:grid-cols-2">
              {#each entries as { item, index } (item.path + index)}
                {@const name = settingNameFor(item)}
                {@const def = getSettingDefinition(name)}
                {#each Object.entries(item.attributes) as [attrKey, value] (attrKey)}
                  <div class="rounded-md border border-border bg-card p-3">
                    <div class="flex flex-col gap-1">
                      <span class="text-xs font-medium text-muted-foreground">
                        {humanizeKey(name)}
                      </span>

                      {#if def?.type === 'select' && def.options}
                        <select
                          class="h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm outline-none focus:ring-1 focus:ring-ring"
                          {value}
                          onchange={(e) => updateAttribute(index, attrKey, e.currentTarget.value)}
                        >
                          {#each def.options as opt (opt.value)}
                            <option value={opt.value}>{opt.label}</option>
                          {/each}
                        </select>
                      {:else if def?.type === 'slider'}
                        <div class="flex items-center gap-2">
                          <input
                            type="range"
                            min={def.min}
                            max={def.max}
                            step={def.step}
                            value={parseFloat(value) || 0}
                            class="theme-slider flex-1"
                            oninput={(e) => updateAttribute(index, attrKey, e.currentTarget.value)}
                          />
                          <span class="w-12 text-right font-mono text-xs text-muted-foreground">
                            {(parseFloat(value) || 0).toFixed(2)}
                          </span>
                        </div>
                      {:else}
                        <input
                          class="h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm outline-none focus:ring-1 focus:ring-ring"
                          type={!Number.isNaN(Number(value)) && value.trim() !== '' ? 'number' : 'text'}
                          {value}
                          oninput={(e) => updateAttribute(index, attrKey, e.currentTarget.value)}
                        />
                      {/if}
                    </div>
                  </div>
                {/each}
              {/each}
            </div>
          </div>
        {/each}
      {/if}
    {/if}

    <div class="flex flex-wrap items-center justify-between gap-2 border-t border-border pt-3">
      <div class="flex flex-wrap items-center gap-2">
        <button
          class="rounded-md border border-border px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground disabled:opacity-40"
          disabled={!clientId || loading}
          onclick={importFromGame}
        >
          Import from Game
        </button>
        <button
          class="rounded-md border border-border px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground disabled:opacity-40"
          disabled={!clientId || loading}
          onclick={loadTemplate}
        >
          Load Full Example
        </button>
        <button
          class="rounded-md bg-primary px-3 py-1.5 text-sm font-semibold text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-40"
          disabled={!clientId || !dirty || loading}
          onclick={save}
        >
          {savedFlash ? 'Saved!' : 'Save Changes'}
        </button>
      </div>
      <button
        class="rounded-md border border-border px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
        onclick={() => (open = false)}
      >
        Close
      </button>
    </div>
  </div>
</Dialog>

// src/renderer/src/components/app/dialogs/GtaSettingsDialog.tsx
import { useMemo } from 'react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import type { GtaSettingsItem } from '@/types'
import { getSettingDefinition, SETTING_CATEGORIES, type SettingOption } from '@shared/gtaSettingsMap'

export type GtaSettingsDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void

  selectedClientId: string | null

  rootName: string
  items: GtaSettingsItem[]

  loading: boolean
  error: string | null
  dirty: boolean

  onImportFromGame: () => void
  onLoadFullExample: () => void
  onSave: () => void

  onUpdateAttribute: (itemId: string, attrKey: string, newValue: string) => void
}

const humanizeKey = (value: string) =>
  value
    .replace(/_/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/\s+/g, ' ')
    .trim()

function renderAttributeInput(
  settingName: string,
  value: string,
  onUpdate: (newValue: string) => void,
  showLabel = true
) {
  const settingDef = getSettingDefinition(settingName)

  if (settingDef?.type === 'select' && settingDef.options) {
    return (
      <div className="flex flex-col gap-1">
        {showLabel && <span className="text-xs font-medium text-muted-foreground">{humanizeKey(settingName)}</span>}
        <select
          className="flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
          value={value}
          onChange={(e) => onUpdate(e.target.value)}
        >
          {settingDef.options.map((opt: SettingOption) => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
      </div>
    )
  }

  if (settingDef?.type === 'slider') {
    const numValue = parseFloat(value) || 0
    return (
      <div className="flex flex-col gap-1">
        {showLabel && <span className="text-xs font-medium text-muted-foreground">{humanizeKey(settingName)}</span>}
        <div className="flex items-center gap-2">
          <input
            type="range"
            min={settingDef.min}
            max={settingDef.max}
            step={settingDef.step}
            value={numValue}
            className="theme-slider flex-1"
            onChange={(e) => onUpdate(e.target.value)}
          />
          <span className="text-xs font-mono text-muted-foreground w-12 text-right">{numValue.toFixed(2)}</span>
        </div>
      </div>
    )
  }

  const numeric = Number(value)
  const isNumeric = !Number.isNaN(numeric) && value.trim() !== ''
  const step = Number.isInteger(numeric) ? 1 : 0.01

  return (
    <div className="flex flex-col gap-1">
      {showLabel && <span className="text-xs font-medium text-muted-foreground">{humanizeKey(settingName)}</span>}
      <Input
        type={isNumeric ? 'number' : 'text'}
        value={value}
        step={isNumeric ? step : undefined}
        onChange={(e: React.ChangeEvent<HTMLInputElement>) => onUpdate(e.target.value)}
      />
    </div>
  )
}

export function GtaSettingsDialog(props: GtaSettingsDialogProps): JSX.Element {
  const {
    open,
    onOpenChange,
    selectedClientId,
    rootName,
    items,
    loading,
    error,
    dirty,
    onImportFromGame,
    onLoadFullExample,
    onSave,
    onUpdateAttribute
  } = props

  const categorizedSettings = useMemo(() => {
    const categories: Record<string, GtaSettingsItem[]> = {}

    items.forEach((item) => {
      const parts = item.path.split('/').filter(Boolean)
      const settingName = parts[parts.length - 1]

      const firstAttrKey = Object.keys(item.attributes)[0]
      const settingDef = getSettingDefinition(settingName || firstAttrKey)

      const category = settingDef?.category || 'Other'

      if (!categories[category]) {
        categories[category] = []
      }
      categories[category].push(item)
    })

    const sorted: Record<string, GtaSettingsItem[]> = {}
    SETTING_CATEGORIES.forEach((cat: string) => {
      if (categories[cat] && categories[cat].length > 0) {
        sorted[cat] = categories[cat]
      }
    })

    if (categories['Other'] && categories['Other'].length > 0) {
      sorted['Other'] = categories['Other']
    }

    return sorted
  }, [items])

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[85vh] max-w-3xl overflow-hidden">
        <DialogHeader>
          <DialogTitle>GTA V Settings Editor</DialogTitle>
          <DialogDescription>
            Edit this client&apos;s settings.xml. These values are saved in the client folder and copied into Documents
            when you launch with GTA Settings enabled.
          </DialogDescription>
        </DialogHeader>

        <div className="mt-4 max-h-[70vh] space-y-3 overflow-y-auto pr-2">
          <div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
            <span>Root element:</span>
            <span className="font-medium text-foreground">{rootName}</span>
            <span className="text-muted-foreground">·</span>
            <span>{items.length} entries</span>
          </div>

          {error && (
            <div className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">
              {error}
            </div>
          )}

          {!loading && !error && (
            <div className="space-y-4">
              {Object.keys(categorizedSettings).length === 0 ? (
                <div className="rounded-md border border-dashed border-border p-4 text-sm text-muted-foreground">
                  No settings found in settings.xml.
                </div>
              ) : (
                Object.entries(categorizedSettings).map(([category, items]) => (
                  <div key={category} className="rounded-md border border-border p-4">
                    <div className="mb-3 flex items-center gap-2">
                      <div className="h-1 w-1 rounded-full bg-primary" />
                      <div className="text-sm font-semibold text-foreground">{category}</div>
                      <div className="text-xs text-muted-foreground">({items.length})</div>
                    </div>

                    <div className="grid gap-3 sm:grid-cols-2">
                      {items.map((item) => {
                        const parts = item.path.split('/').filter(Boolean)
                        const settingName = parts[parts.length - 1]
                        const entries = Object.entries(item.attributes)

                        return entries.map(([attrKey, value]) => (
                          <div key={`${item.id}-${attrKey}`} className="rounded-md border border-border bg-card p-3">
                            {renderAttributeInput(settingName, value, (newValue) => onUpdateAttribute(item.id, attrKey, newValue), true)}
                          </div>
                        ))
                      })}
                    </div>
                  </div>
                ))
              )}
            </div>
          )}

          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex flex-wrap items-center gap-2">
              <Button variant="secondary" disabled={!selectedClientId || loading} onClick={onImportFromGame}>
                Import from Game
              </Button>
              <Button variant="outline" disabled={!selectedClientId || loading} onClick={onLoadFullExample}>
                Load Full Example
              </Button>
              <Button variant="default" disabled={!selectedClientId || !dirty || loading} onClick={onSave}>
                Save Changes
              </Button>
            </div>
            <Button variant="secondary" onClick={() => onOpenChange(false)}>
              Close
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
