// src/renderer/src/App.tsx
import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@/components/ui/card'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from '@/components/ui/dialog'
import type { ClientProfile, LinkOptions } from '@/types'

function App(): JSX.Element {
  const [selectedClient, setSelectedClient] = useState<string | null>(null)
  const [clients, setClients] = useState<ClientProfile[]>([])
  const [newClientName, setNewClientName] = useState('')
  const [renameValue, setRenameValue] = useState('')
  const [createOpen, setCreateOpen] = useState(false)
  const [firstRunOpen, setFirstRunOpen] = useState(false)

  useEffect(() => {
    loadClients()
  }, [])

  useEffect(() => {
    const acknowledged = localStorage.getItem('fivelaunch.firstRunAck')
    if (!acknowledged) {
      setFirstRunOpen(true)
    }
  }, [])

  const loadClients = async () => {
    const data = await window.api.getClients()
    setClients(data)
  }

  const handleCreate = async () => {
    if (!newClientName) return
    await window.api.createClient(newClientName)
    setNewClientName('')
    loadClients()
    setCreateOpen(false)
  }

  const handleDelete = async (id: string, e: React.MouseEvent<HTMLButtonElement>) => {
    e.stopPropagation()
    const client = clients.find((c) => c.id === id)
    const name = client?.name || 'this client'
    const confirmed = window.confirm(`Delete ${name}? This will remove its local folder.`)
    if (!confirmed) return
    await window.api.deleteClient(id)
    if (selectedClient === id) setSelectedClient(null)
    loadClients()
  }

  const handleLaunch = () => {
    if (selectedClient) {
      console.log(`Launching client: ${selectedClient}`)
      window.api.launchClient(selectedClient)
    }
  }

  const handleOpenFolder = async () => {
    if (!selectedClient) return
    await window.api.openClientFolder(selectedClient)
  }

  const handleRename = async () => {
    if (!selectedClientData) return
    const trimmed = renameValue.trim()
    if (!trimmed) return
    await window.api.renameClient(selectedClientData.id, trimmed)
    setRenameValue('')
    loadClients()
  }

  const handleToggleLink = async (key: keyof LinkOptions) => {
    if (!selectedClientData) return
    const updated: LinkOptions = {
      ...selectedClientData.linkOptions,
      [key]: !selectedClientData.linkOptions[key]
    }
    await window.api.updateClientLinks(selectedClientData.id, updated)
    setClients((prev) =>
      prev.map((c) => (c.id === selectedClientData.id ? { ...c, linkOptions: updated } : c))
    )
  }

  const selectedClientData = clients.find((c) => c.id === selectedClient) || null
  useEffect(() => {
    setRenameValue(selectedClientData?.name || '')
  }, [selectedClientData?.id])
    const handleFirstRunContinue = () => {
      localStorage.setItem('fivelaunch.firstRunAck', 'true')
      setFirstRunOpen(false)
    }

    const handleResetFirstRun = () => {
      localStorage.removeItem('fivelaunch.firstRunAck')
      setFirstRunOpen(true)
    }
  const lastPlayedText = selectedClientData?.lastPlayed
    ? new Date(selectedClientData.lastPlayed).toLocaleString()
    : 'Never'

    const commitInfo = __COMMIT_INFO__
    const repoUrl = __REPO_URL__

  return (
    <div className="min-h-screen w-full bg-background">
      <div className="titlebar fixed left-0 top-0 z-50 flex h-10 w-full items-center justify-between border-b border-border bg-card px-3">
        <div className="text-sm font-semibold">FiveLaunch</div>
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" onClick={() => window.api.windowMinimize()}>
            _
          </Button>
          <Button variant="ghost" size="sm" onClick={() => window.api.windowToggleMaximize()}>
            □
          </Button>
          <Button variant="ghost" size="sm" onClick={() => window.api.windowClose()}>
            ×
          </Button>
        </div>
      </div>

      <div className="p-6 pt-16">
        <Dialog
          open={firstRunOpen}
          onOpenChange={(open) => {
            if (!open) {
              localStorage.setItem('fivelaunch.firstRunAck', 'true')
            }
            setFirstRunOpen(open)
          }}
        >
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Welcome to FiveLaunch</DialogTitle>
              <DialogDescription>
                Before linking files, please back up your original FiveM data. We will rename
                existing folders and settings files the first time you link a client.
              </DialogDescription>
            </DialogHeader>

            <div className="mt-4 space-y-4 text-sm">
              <div className="rounded-md border border-border p-4">
                <div className="font-medium">Back up these items</div>
                <ul className="mt-2 list-disc space-y-1 pl-5 text-muted-foreground">
                  <li>FiveM.app folders: mods, plugins, citizen</li>
                  <li>GTA settings: gta5_settings.xml</li>
                  <li>CitizenFX.ini</li>
                </ul>
              </div>

              <div className="rounded-md border border-border p-4">
                <div className="font-medium">Where they live</div>
                <div className="mt-2 space-y-1 text-muted-foreground">
                  <div>
                    CitizenFX folder: <span className="text-foreground">%APPDATA%\CitizenFX</span>
                  </div>
                  <div>
                    FiveM app data: <span className="text-foreground">%LOCALAPPDATA%\FiveM\FiveM.app</span>
                  </div>
                </div>
                <div className="mt-3 flex flex-wrap gap-2">
                  <Button variant="secondary" onClick={() => window.api.openCitizenFxFolder()}>
                    Open CitizenFX Folder
                  </Button>
                  <Button variant="secondary" onClick={() => window.api.openFiveMFolder()}>
                    Open FiveM Folder
                  </Button>
                </div>
              </div>

              <div className="flex items-center justify-end gap-2">
                <Button onClick={handleFirstRunContinue}>I Understand</Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
        <div className="mx-auto max-w-5xl">
          <div className="mb-6 flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-semibold">FiveLaunch Clients</h1>
              <p className="text-sm text-muted-foreground">
                Create profiles, manage links, and launch FiveM.
              </p>
            </div>
            <Dialog open={createOpen} onOpenChange={setCreateOpen}>
              <DialogTrigger asChild>
                <Button size="sm" aria-label="Create client">
                  + New Client
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Create New Client</DialogTitle>
                  <DialogDescription>
                    Give your client a name. You can edit details later.
                  </DialogDescription>
                </DialogHeader>
                <div className="mt-4 flex flex-col gap-2 sm:flex-row">
                  <Input
                    placeholder="New client name"
                    value={newClientName}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                      setNewClientName(e.target.value)
                    }
                  />
                  <Button onClick={handleCreate} disabled={!newClientName.trim()}>
                    Create
                  </Button>
                </div>
              </DialogContent>
            </Dialog>
          </div>

          <div className="grid gap-6 lg:grid-cols-[300px_1fr]">
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Client List</CardTitle>
                <CardDescription>Pick a client to view details.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-2">
                {clients.length === 0 && (
                  <div className="rounded-md border border-dashed border-border p-6 text-center text-sm text-muted-foreground">
                    No clients yet. Create one to get started.
                  </div>
                )}
                {clients.map((client) => (
                  <button
                    key={client.id}
                    className={`w-full rounded-md border px-3 py-2 text-left text-sm transition-colors ${
                      selectedClient === client.id
                        ? 'border-primary bg-primary/10 text-foreground'
                        : 'border-border bg-card text-muted-foreground hover:text-foreground'
                    }`}
                    onClick={() =>
                      setSelectedClient((prev) => (prev === client.id ? null : client.id))
                    }
                  >
                    <div className="font-medium text-foreground">{client.name}</div>
                    <div className="text-xs text-muted-foreground">{client.id}</div>
                  </button>
                ))}
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-base">Client Overview</CardTitle>
                <CardDescription>Review and launch your selected client.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="rounded-md border border-border p-4 text-sm">
                  <div className="grid gap-2 text-muted-foreground">
                    <div>
                      <span className="text-foreground">Name:</span>{' '}
                      {selectedClientData?.name || '—'}
                    </div>
                    <div>
                      <span className="text-foreground">ID:</span>{' '}
                      {selectedClientData?.id || '—'}
                    </div>
                    <div>
                      <span className="text-foreground">Last Played:</span> {lastPlayedText}
                    </div>
                  </div>
                </div>

                <div className="flex flex-wrap gap-2">
                  <Dialog>
                    <DialogTrigger asChild>
                      <Button variant="secondary" disabled={!selectedClientData}>
                        Client Options
                      </Button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>Client Options</DialogTitle>
                        <DialogDescription>
                          Configure links, rename the client, or open the client folder.
                        </DialogDescription>
                      </DialogHeader>

                      <div className="mt-4 space-y-4">
                        <div className="flex flex-col gap-2 sm:flex-row">
                          <Input
                            placeholder="Rename client"
                            value={renameValue}
                            onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                              setRenameValue(e.target.value)
                            }
                            disabled={!selectedClientData}
                          />
                          <Button
                            variant="secondary"
                            onClick={handleRename}
                            disabled={!selectedClientData || !renameValue.trim()}
                          >
                            Rename
                          </Button>
                        </div>

                        <div className="rounded-md border border-border p-4 text-sm">
                          <div className="font-medium">Link Options</div>
                          <div className="mt-3 grid gap-2 text-muted-foreground">
                            {(
                              [
                                ['mods', 'Mods'],
                                ['plugins', 'Plugins'],
                                ['citizen', 'Citizen'],
                                ['gtaSettings', 'GTA Settings (gta5_settings.xml)'],
                                ['citizenFxIni', 'CitizenFX.ini']
                              ] as const
                            ).map(([key, label]) => (
                              <label key={key} className="flex items-center gap-2">
                                <input
                                  type="checkbox"
                                  className="h-4 w-4 accent-primary"
                                  disabled={!selectedClientData}
                                  checked={!!selectedClientData?.linkOptions?.[key]}
                                  onChange={() => handleToggleLink(key)}
                                />
                                <span>{label}</span>
                              </label>
                            ))}
                          </div>
                        </div>

                        <div className="flex flex-wrap gap-2">
                          <Button
                            variant="secondary"
                            disabled={!selectedClientData}
                            onClick={handleOpenFolder}
                          >
                            Open Client Folder
                          </Button>
                          <Button
                            variant="destructive"
                            disabled={!selectedClientData}
                            onClick={(e: React.MouseEvent<HTMLButtonElement>) =>
                              selectedClientData && handleDelete(selectedClientData.id, e)
                            }
                          >
                            Delete Client
                          </Button>
                        </div>
                      </div>
                    </DialogContent>
                  </Dialog>

                  <Button disabled={!selectedClientData} onClick={handleLaunch}>
                    Launch Game
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        <footer className="mx-auto mt-8 flex max-w-5xl flex-col items-start justify-between gap-2 border-t border-border pt-4 text-xs text-muted-foreground sm:flex-row sm:items-center">
          <div className="flex flex-wrap items-center gap-3">
            <span>© {new Date().getFullYear()} FiveLaunch</span>
            <a href={repoUrl} target="_blank" rel="noreferrer" className="hover:text-foreground">
              Open Source
            </a>
            <a
              href="https://fivelaunch.help/support"
              target="_blank"
              rel="noreferrer"
              className="hover:text-foreground"
            >
              Help & Support
            </a>
            {import.meta.env.DEV && (
              <button
                onClick={handleResetFirstRun}
                className="hover:text-foreground"
                type="button"
              >
                Reset First-Run
              </button>
            )}
          </div>
          {commitInfo ? (
            <a
              href={commitInfo.url}
              target="_blank"
              rel="noreferrer"
              title={`Commit ${commitInfo.shortSha} · ${commitInfo.message}\nAPI: ${commitInfo.apiUrl}`}
              className="hover:text-foreground"
            >
              Commit {commitInfo.shortSha} ·{' '}
              {commitInfo.date ? new Date(commitInfo.date).toLocaleDateString() : '—'}
            </a>
          ) : (
            <span className="text-muted-foreground">Commit info available in build</span>
          )}
        </footer>
      </div>
    </div>
  )
}

export default App

// src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import TitleBar from './lib/components/TitleBar.svelte'
  import SettingsDialog from './lib/components/SettingsDialog.svelte'
  import FirstRunDialog from './lib/components/FirstRunDialog.svelte'
  import RefsDialog from './lib/components/RefsDialog.svelte'
  import ClientDetailsDialog from './lib/components/ClientDetailsDialog.svelte'
  import GtaSettingsDialog from './lib/components/GtaSettingsDialog.svelte'
  import LogsPanel from './lib/components/LogsPanel.svelte'
  import { api } from './lib/api'
  import { formatBytes } from './lib/format'
  import { applyPrimaryHexToRoot, DEFAULT_PRIMARY_HEX } from './lib/theme'
  import type { AppLogEntry, ClientProfile, ClientStats } from './lib/types'

  const FIRST_RUN_ACK_KEY = 'fivelaunch.firstRunAck'

  let clients = $state<ClientProfile[]>([])
  let selectedId = $state<string | null>(null)
  let query = $state('')
  let newName = $state('')
  let renameValue = $state('')
  let renaming = $state(false)
  let confirmingDelete = $state(false)
  let stats = $state<ClientStats | null>(null)
  let appVersion = $state('')
  let resolvedGamePath = $state<string | null>(null)
  let error = $state<string | null>(null)
  let launching = $state(false)
  let launchStatus = $state<string | null>(null)
  let pluginsSyncBusy = $state(false)

  // Dialogs / panels
  let settingsOpen = $state(false)
  let firstRunOpen = $state(false)
  let refsOpen = $state(false)
  let detailsOpen = $state(false)
  let gtaSettingsOpen = $state(false)
  let logsOpen = $state(false)

  // Launch log store (fed by launch-status events)
  let logs = $state<AppLogEntry[]>([])
  let logSeq = 0

  function pushLog(message: string): void {
    logSeq += 1
    const level: AppLogEntry['level'] = message.startsWith('WARNING')
      ? 'warn'
      : message.toLowerCase().includes('error') || message.toLowerCase().includes('failed')
        ? 'error'
        : 'info'
    logs = [...logs, { id: logSeq, ts: Date.now(), level, message, source: 'launch' }]
    if (logs.length > 1000) logs = logs.slice(logs.length - 1000)
  }

  const filtered = $derived(
    clients.filter((c) => c.name.toLowerCase().includes(query.trim().toLowerCase()))
  )
  const selected = $derived(clients.find((c) => c.id === selectedId) ?? null)

  type LinkKey = 'mods' | 'plugins' | 'citizen' | 'gtaSettings' | 'citizenFxIni'

  const linkChips = $derived.by(() => {
    if (!selected) return []
    const o = selected.linkOptions
    const chips: { key: LinkKey; label: string; on: boolean; hint: string }[] = [
      { key: 'mods', label: 'Mods', on: o.mods, hint: 'Link the mods folder' },
      {
        key: 'plugins',
        label: `Plugins${o.plugins ? ` (${o.pluginsMode ?? 'sync'})` : ''}`,
        on: o.plugins,
        hint: 'Click to cycle: off → sync (copy) → junction → off'
      },
      { key: 'citizen', label: 'Citizen', on: o.citizen, hint: 'Link the citizen folder (advanced)' },
      {
        key: 'gtaSettings',
        label: 'GTA settings',
        on: o.gtaSettings,
        hint: 'Apply + enforce this client’s gta5_settings.xml'
      },
      {
        key: 'citizenFxIni',
        label: 'CitizenFX.ini',
        on: o.citizenFxIni,
        hint: 'Seed + sync this client’s CitizenFX.ini'
      }
    ]
    return chips
  })

  async function toggleLink(key: LinkKey): Promise<void> {
    if (!selected) return
    const o = { ...selected.linkOptions }
    if (key === 'plugins') {
      // Cycle: off -> sync (copy) -> junction -> off
      if (!o.plugins) {
        o.plugins = true
        o.pluginsMode = 'sync'
      } else if ((o.pluginsMode ?? 'sync') === 'sync') {
        o.pluginsMode = 'junction'
      } else {
        o.plugins = false
      }
    } else {
      o[key] = !o[key]
    }
    try {
      await api.updateClientLinks(selected.id, o)
      await refresh()
    } catch (e) {
      error = String(e)
    }
  }

  async function refresh(): Promise<void> {
    clients = await api.getClients()
    if (selectedId && !clients.some((c) => c.id === selectedId)) {
      selectedId = null
    }
  }

  onMount(() => {
    firstRunOpen = localStorage.getItem(FIRST_RUN_ACK_KEY) !== 'true'

    let unlistenFn: (() => void) | null = null
    api
      .onLaunchStatus((status) => {
        launchStatus = status
        pushLog(status)
      })
      .then((fn) => (unlistenFn = fn))
      .catch(() => {})

    const pollBusy = () => {
      api
        .getGameBusyState()
        .then((s) => (pluginsSyncBusy = s.pluginsSyncBusy))
        .catch(() => {})
    }
    pollBusy()
    const busyTimer = setInterval(pollBusy, 3000)

    void (async () => {
      try {
        const settings = await api.getSettings()
        applyPrimaryHexToRoot(settings.themePrimaryHex ?? DEFAULT_PRIMARY_HEX)
        ;[appVersion, resolvedGamePath] = await Promise.all([
          api.getAppVersion(),
          api.getResolvedGamePath()
        ])
        await refresh()
      } catch (e) {
        error = String(e)
      }
    })()

    return () => {
      clearInterval(busyTimer)
      unlistenFn?.()
    }
  })

  async function launchSelected(): Promise<void> {
    if (!selected || launching) return
    launching = true
    launchStatus = 'Preparing launch...'
    try {
      await api.launchClient(selected.id)
    } catch (e) {
      error = String(e)
      launchStatus = null
    } finally {
      launching = false
    }
  }

  $effect(() => {
    const id = selectedId
    stats = null
    confirmingDelete = false
    renaming = false
    if (!id) return
    api
      .getClientStats(id)
      .then((s) => {
        if (selectedId === id) stats = s
      })
      .catch(() => {})
  })

  async function createClient(): Promise<void> {
    const name = newName.trim()
    if (!name) return
    try {
      const created = await api.createClient(name)
      newName = ''
      await refresh()
      selectedId = created.id
    } catch (e) {
      error = String(e)
    }
  }

  async function applyRename(): Promise<void> {
    if (!selected) return
    const name = renameValue.trim()
    if (!name || name === selected.name) {
      renaming = false
      return
    }
    try {
      await api.renameClient(selected.id, name)
      renaming = false
      await refresh()
    } catch (e) {
      error = String(e)
    }
  }

  async function deleteSelected(): Promise<void> {
    if (!selected) return
    if (!confirmingDelete) {
      confirmingDelete = true
      return
    }
    try {
      await api.deleteClient(selected.id)
      confirmingDelete = false
      await refresh()
    } catch (e) {
      error = String(e)
    }
  }

  function formatLastPlayed(ts?: number): string {
    if (!ts) return 'Never'
    return new Date(ts).toLocaleString()
  }

  function acknowledgeFirstRun(): void {
    localStorage.setItem(FIRST_RUN_ACK_KEY, 'true')
    firstRunOpen = false
  }

  async function refreshResolvedPath(): Promise<void> {
    try {
      resolvedGamePath = await api.getResolvedGamePath()
    } catch {
      // ignore
    }
  }
</script>

<div class="flex h-screen flex-col bg-background text-foreground">
  <TitleBar {appVersion} onOpenSettings={() => (settingsOpen = true)} />

  <main class="grid min-h-0 flex-1 grid-cols-[320px_1fr] gap-4 p-4">
    <!-- Client list -->
    <section class="flex min-h-0 flex-col rounded-lg border border-border bg-card">
      <div class="border-b border-border p-3">
        <h2 class="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          Clients
        </h2>
        <input
          class="w-full rounded-md border border-input bg-secondary/40 px-3 py-1.5 text-sm outline-none placeholder:text-muted-foreground focus:ring-1 focus:ring-ring"
          placeholder="Search clients..."
          bind:value={query}
        />
      </div>

      <div class="min-h-0 flex-1 overflow-y-auto p-2">
        {#if filtered.length === 0}
          <p class="px-2 py-6 text-center text-sm text-muted-foreground">
            {clients.length === 0 ? 'No clients yet. Create one below.' : 'No matches.'}
          </p>
        {:else}
          {#each filtered as client (client.id)}
            <button
              class="mb-1 flex w-full flex-col rounded-md px-3 py-2 text-left transition-colors {selectedId ===
              client.id
                ? 'bg-primary/15 text-foreground ring-1 ring-primary/40'
                : 'hover:bg-secondary/60'}"
              onclick={() => (selectedId = client.id)}
            >
              <span class="truncate text-sm font-medium">{client.name}</span>
              <span class="truncate text-xs text-muted-foreground">
                Last played: {formatLastPlayed(client.lastPlayed)}
              </span>
            </button>
          {/each}
        {/if}
      </div>

      <div class="flex gap-2 border-t border-border p-3">
        <input
          class="min-w-0 flex-1 rounded-md border border-input bg-secondary/40 px-3 py-1.5 text-sm outline-none placeholder:text-muted-foreground focus:ring-1 focus:ring-ring"
          placeholder="New client name"
          bind:value={newName}
          onkeydown={(e) => e.key === 'Enter' && createClient()}
        />
        <button
          class="shrink-0 rounded-md bg-primary px-3 py-1.5 text-sm font-semibold text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-40"
          disabled={!newName.trim()}
          onclick={createClient}
        >
          Create
        </button>
      </div>
    </section>

    <!-- Overview -->
    <section class="flex min-h-0 flex-col rounded-lg border border-border bg-card">
      {#if !selected}
        <div class="flex flex-1 items-center justify-center">
          <p class="text-sm text-muted-foreground">Select a client to see its details.</p>
        </div>
      {:else}
        <div class="flex items-start justify-between border-b border-border p-4">
          <div class="min-w-0">
            {#if renaming}
              <div class="flex items-center gap-2">
                <input
                  class="rounded-md border border-input bg-secondary/40 px-3 py-1.5 text-lg font-semibold outline-none focus:ring-1 focus:ring-ring"
                  bind:value={renameValue}
                  onkeydown={(e) => {
                    if (e.key === 'Enter') applyRename()
                    if (e.key === 'Escape') renaming = false
                  }}
                />
                <button
                  class="rounded-md bg-primary px-3 py-1.5 text-sm font-semibold text-primary-foreground hover:opacity-90"
                  onclick={applyRename}
                >
                  Save
                </button>
              </div>
            {:else}
              <h1 class="truncate text-xl font-bold">{selected.name}</h1>
            {/if}
            <p class="mt-1 font-mono text-xs text-muted-foreground">{selected.id}</p>
          </div>

          <div class="flex shrink-0 gap-2 pl-4">
            <button
              class="rounded-md border border-border px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
              onclick={() => {
                renameValue = selected?.name ?? ''
                renaming = true
              }}
            >
              Rename
            </button>
            <button
              class="rounded-md border px-3 py-1.5 text-sm transition-colors {confirmingDelete
                ? 'border-destructive bg-destructive text-destructive-foreground'
                : 'border-border text-muted-foreground hover:bg-secondary hover:text-foreground'}"
              onclick={deleteSelected}
              onmouseleave={() => (confirmingDelete = false)}
            >
              {confirmingDelete ? 'Confirm delete?' : 'Delete'}
            </button>
          </div>
        </div>

        <div class="grid grid-cols-3 gap-3 p-4">
          <div class="rounded-md border border-border bg-secondary/30 p-3">
            <p class="text-xs uppercase tracking-wider text-muted-foreground">Files</p>
            <p class="mt-1 text-lg font-semibold">
              {stats ? stats.fileCount.toLocaleString() : '…'}
            </p>
          </div>
          <div class="rounded-md border border-border bg-secondary/30 p-3">
            <p class="text-xs uppercase tracking-wider text-muted-foreground">Size</p>
            <p class="mt-1 text-lg font-semibold">{stats ? formatBytes(stats.totalBytes) : '…'}</p>
          </div>
          <div class="rounded-md border border-border bg-secondary/30 p-3">
            <p class="text-xs uppercase tracking-wider text-muted-foreground">Last played</p>
            <p class="mt-1 truncate text-lg font-semibold">
              {formatLastPlayed(selected.lastPlayed)}
            </p>
          </div>
        </div>

        <div class="px-4">
          <p class="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            Linking
          </p>
          <div class="flex flex-wrap gap-2">
            {#each linkChips as chip (chip.key)}
              <button
                class="rounded-full border px-3 py-1 text-xs transition-colors {chip.on
                  ? 'border-primary/50 bg-primary/15 text-foreground hover:bg-primary/25'
                  : 'border-border text-muted-foreground hover:bg-secondary/60 hover:text-foreground'}"
                title={chip.hint}
                onclick={() => toggleLink(chip.key)}
              >
                {chip.label}
              </button>
            {/each}
          </div>
        </div>

        <div class="mt-auto flex flex-wrap gap-2 p-4">
          <button
            class="rounded-md border border-border px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
            onclick={() => (detailsOpen = true)}
          >
            Details
          </button>
          <button
            class="rounded-md border border-border px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
            onclick={() => (gtaSettingsOpen = true)}
            title="Edit this client's gta5_settings.xml"
          >
            Edit GTA settings
          </button>
          <button
            class="rounded-md border border-border px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
            onclick={() => (refsOpen = true)}
            title="Quick links to useful folders"
          >
            Refs
          </button>
          <button
            class="ml-auto rounded-md bg-primary px-5 py-1.5 text-sm font-semibold text-primary-foreground transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"
            disabled={launching || pluginsSyncBusy}
            title={pluginsSyncBusy ? 'Waiting for the previous plugins sync to finish' : undefined}
            onclick={launchSelected}
          >
            {launching ? 'Launching…' : pluginsSyncBusy ? 'Sync busy…' : 'Launch'}
          </button>
        </div>

        {#if launchStatus}
          <div class="flex items-center gap-2 border-t border-border px-4 py-2">
            {#if launching}
              <span
                class="h-3 w-3 shrink-0 animate-spin rounded-full border-2 border-muted border-t-primary"
              ></span>
            {/if}
            <p
              class="truncate text-xs {launchStatus.startsWith('WARNING')
                ? 'text-destructive-foreground'
                : 'text-muted-foreground'}"
            >
              {launchStatus}
            </p>
          </div>
        {/if}
      {/if}
    </section>
  </main>

  {#if logsOpen}
    <div class="px-4 pb-2">
      <LogsPanel {logs} onClear={() => (logs = [])} />
    </div>
  {/if}

  {#if error}
    <div class="mx-4 mb-2 rounded-md border border-destructive bg-destructive/20 px-3 py-2 text-sm">
      {error}
      <button class="ml-2 underline" onclick={() => (error = null)}>dismiss</button>
    </div>
  {/if}

  <footer
    class="flex h-8 shrink-0 items-center justify-between border-t border-border px-4 text-xs text-muted-foreground"
  >
    <span class="flex items-center gap-2">
      FiveLaunch v{appVersion || '…'} (Tauri)
      {#if pluginsSyncBusy}
        <span class="rounded-full border border-primary/50 bg-primary/15 px-2 py-0.5 text-[10px]">
          plugins sync running
        </span>
      {/if}
      <button
        class="rounded px-1.5 py-0.5 transition-colors hover:bg-secondary hover:text-foreground {logsOpen
          ? 'text-foreground'
          : ''}"
        onclick={() => (logsOpen = !logsOpen)}
      >
        Logs{logs.length ? ` (${logs.length})` : ''}
      </button>
    </span>
    <span class="truncate pl-4 font-mono">
      {resolvedGamePath ?? 'FiveM not found — set the game path in settings'}
    </span>
  </footer>

  <SettingsDialog bind:open={settingsOpen} onSaved={refreshResolvedPath} />
  <FirstRunDialog bind:open={firstRunOpen} onContinue={acknowledgeFirstRun} />
  <RefsDialog bind:open={refsOpen} client={selected} />
  <ClientDetailsDialog bind:open={detailsOpen} client={selected} {stats} onChanged={refresh} />
  <GtaSettingsDialog bind:open={gtaSettingsOpen} clientId={selectedId} />
</div>
