// v1/src/renderer/src/components/app/dialogs/RefsDialog.tsx
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import type { ClientProfile } from '@/types'
import { FolderOpen } from 'lucide-react'

export type RefsDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void

  client: ClientProfile | null

  onOpenClientFolder: () => void
  onOpenClientPluginsFolder: () => void
  onOpenFiveMFolder: () => void
  onOpenFiveMPluginsFolder: () => void
  onOpenCitizenFxFolder: () => void
}

export function RefsDialog(props: RefsDialogProps): JSX.Element {
  const {
    open,
    onOpenChange,
    client,
    onOpenClientFolder,
    onOpenClientPluginsFolder,
    onOpenFiveMFolder,
    onOpenFiveMPluginsFolder,
    onOpenCitizenFxFolder
  } = props

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Refs</DialogTitle>
          <DialogDescription>Quick links to open useful folders.</DialogDescription>
        </DialogHeader>

        <div className="mt-4 grid gap-2 sm:grid-cols-2">
          <Button variant="secondary" disabled={!client} onClick={onOpenClientFolder}>
            <FolderOpen className="h-4 w-4" />
            Client Folder
          </Button>
          <Button variant="secondary" disabled={!client} onClick={onOpenClientPluginsFolder}>
            <FolderOpen className="h-4 w-4" />
            Client Plugins
          </Button>
          <Button variant="secondary" onClick={onOpenFiveMFolder}>
            <FolderOpen className="h-4 w-4" />
            FiveM Folder
          </Button>
          <Button variant="secondary" onClick={onOpenFiveMPluginsFolder}>
            <FolderOpen className="h-4 w-4" />
            FiveM Plugins
          </Button>
          <Button variant="secondary" onClick={onOpenCitizenFxFolder}>
            <FolderOpen className="h-4 w-4" />
            CitizenFX Folder
          </Button>
          <Button variant="secondary" onClick={() => onOpenChange(false)}>
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}

// src/lib/components/RefsDialog.svelte
<script lang="ts">
  import Dialog from './ui/Dialog.svelte'
  import { api } from '../api'
  import type { ClientProfile } from '../types'

  let {
    open = $bindable(false),
    client
  }: {
    open?: boolean
    client: ClientProfile | null
  } = $props()

  let error = $state<string | null>(null)

  function run(action: Promise<void>): void {
    error = null
    action.catch((e) => (error = String(e)))
  }
</script>

<Dialog bind:open title="Refs" description="Quick links to open useful folders.">
  <div class="mt-3 grid gap-2 sm:grid-cols-2">
    <button
      class="rounded-md border border-border px-3 py-2 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground disabled:opacity-40"
      disabled={!client}
      onclick={() => client && run(api.openClientFolder(client.id))}
    >
      Client Folder
    </button>
    <button
      class="rounded-md border border-border px-3 py-2 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground disabled:opacity-40"
      disabled={!client}
      onclick={() => client && run(api.openClientPluginsFolder(client.id))}
    >
      Client Plugins
    </button>
    <button
      class="rounded-md border border-border px-3 py-2 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
      onclick={() => run(api.openFiveMFolder())}
    >
      FiveM Folder
    </button>
    <button
      class="rounded-md border border-border px-3 py-2 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
      onclick={() => run(api.openFiveMPluginsFolder())}
    >
      FiveM Plugins
    </button>
    <button
      class="rounded-md border border-border px-3 py-2 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
      onclick={() => run(api.openCitizenFxFolder())}
    >
      CitizenFX Folder
    </button>
    <button
      class="rounded-md border border-border px-3 py-2 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
      onclick={() => (open = false)}
    >
      Close
    </button>
  </div>

  {#if error}
    <div class="mt-3 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm">
      {error}
    </div>
  {/if}
</Dialog>
